[package]
name = "sola"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2"
structopt = "0.3"
inkwell = { version = "0.5.0", features = ["llvm18-0"] }
chumsky = "0.9.3"
ariadne = "0.5.0"
logos = "0.15.0"
id_collections = "1.0.1"
ustr = "1.1.0"
