[package]
name = "sola"
version = "0.1.0"
edition = "2021"

[dependencies]
lalrpop-util = { version = "0.22.0", features = ["lexer", "unicode"] }

colored = "2"
structopt = "0.3"

[build-dependencies]
lalrpop = "0.22.0"
